In [1]:
import math
import numpy as np
k = 2
L = np.array([0.0,0.0])
p = np.array([0.5,0.5])
e = 0
eta = 1
eta = math.sqrt(math.log(k)/(2**e))

l = np.array([0.7, 0.3])




In [2]:
for e in range(0,10):
    eta = math.sqrt(math.log(k)/(2**e))
    print(eta)

0.8325546111576977
0.5887050112577373
0.41627730557884884
0.29435250562886867
0.20813865278942442
0.14717625281443433
0.10406932639471221
0.07358812640721717
0.052034663197356106
0.03679406320360858


In [3]:
for x in range(0,10):
    y = math.e**(-x/100)
    print(y)

1.0
0.9900498337491681
0.9801986733067553
0.9704455335485082
0.9607894391523232
0.951229424500714
0.9417645335842487
0.9323938199059483
0.9231163463866358
0.9139311852712282


In [43]:
eta

0.8325546111576977

In [71]:

i = 0
newL = np.copy(L)
for x in range(0,10):
    newL[i] = L[i] + eta*((x)/p[i])
    print(newL)
    m = math.e**(-newL)
    newP = np.copy(p)
    for j in range(0,k):
        newP[j] = m[j]/sum(m)
    print(newP)


[0. 0.]
[0.5 0.5]
[0.07358813 0.        ]
[0.48161127 0.51838873]
[0.14717625 0.        ]
[0.46327221 0.53672779]
[0.22076438 0.        ]
[0.44503197 0.55496803]
[0.29435251 0.        ]
[0.42693864 0.57306136]
[0.36794063 0.        ]
[0.40903873 0.59096127]
[0.44152876 0.        ]
[0.39137676 0.60862324]
[0.51511688 0.        ]
[0.37399478 0.62600522]
[0.58870501 0.        ]
[0.35693204 0.64306796]
[0.66229314 0.        ]
[0.34022468 0.65977532]


In [52]:
L

array([0., 0.])

In [53]:
newL

array([0.        , 0.49953277])

In [54]:
math.e**(-newL)

array([1.        , 0.60681412])

In [58]:
m = math.e**(-newL)
newP = np.copy(p)
for i in range(0,k):
    newP[i] = m[i]/sum(m)

In [59]:
m

array([1.        , 0.60681412])

In [60]:
newP

array([0.62234952, 0.37765048])